### ISSUE TITLE
official git repo?

### ISSUE THREAD

**Issue by sunaku** [fadein/vim-FIGlet#1]
Is this git repo supposed to replace your previous https://github.com/fadein/FIGlet.vim one?  Because this one only has history from v3.1 onwards, whereas the previous one has history going back to version 1.0.

Could you please restore prior history into this repo *or* commit v3.1 onwards into the previous repo? :sweat_smile:

Thanks for your consideration.

**Comment by fadein** [comment]
I kinda forgot about the other repo. Thanks for reminding me! I'll deactivate the other one and migrate its history into this repo.

**Comment by fadein** [comment]
I've updated the documentation on both repos to indicate that this one is now considered official.

**Comment by sunaku** [comment]
Thanks!  :+1: Would you also mind:
1. Rebasing this repo on top of commit 2dc88b2c36bd666abcfd14e63ef36f4360465095 from the old one 
2. Force-pushing the result back to this repo

This way, the commit history from your old repo won't be lost :sweat_smile: and this also helps us see exactly what changed in v3.1 by looking at the commit diff (which currently includes *all* changes :scream:  from zero to v3.1).
