### ISSUE TITLE
-w76-- displayed after text

### ISSUE THREAD

**Issue by theniceboy** [fadein/vim-FIGlet#2]
Hi! I love this plugin but I every time when I run `:FIGlet ...` it always produces a text shape of `-w76--` right after. For example, this is the output of `:FIGlet demo`:

```
     _                                        _____ __                  
  __| | ___ _ __ ___   ___        __      __ |___  / /_                 
 / _` |/ _ \ '_ ` _ \ / _ \   ____\ \ /\ / /    / / '_ \   _____ _____  
| (_| |  __/ | | | | | (_) | |_____\ V  V /    / /| (_) | |_____|_____| 
 \__,_|\___|_| |_| |_|\___/         \_/\_/    /_/  \___/                
                                                                        
```

Is there a solution for this?

Thank you!

**Comment by fadein** [comment]
> Hi! I love this plugin but I every time when I run `:FIGlet ...` it always produces a text shape of `-w76--` right after. For example, this is the output of `:FIGlet demo`:
> 
> ```
>      _                                        _____ __                  
>   __| | ___ _ __ ___   ___        __      __ |___  / /_                 
>  / _` |/ _ \ '_ ` _ \ / _ \   ____\ \ /\ / /    / / '_ \   _____ _____  
> | (_| |  __/ | | | | | (_) | |_____\ V  V /    / /| (_) | |_____|_____| 
>  \__,_|\___|_| |_| |_|\___/         \_/\_/    /_/  \___/                
>                                                                         
> ```
> 
> Is there a solution for this?
> 
> Thank you!

I take it you solved this yourself.  I have been unable to reproduce this problem.  Out of curiosity, do you know what you did to fix it?

**Comment by theniceboy** [comment]
I couldn’t figure it out so I thought I would just have to use `:r !figlet [text]`
